//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendTech.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTS_DATA_VTWEB_TRANSACTIONDETALS__JULY_13___AUG_8___2024
    {
        public string RTSUID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string MeterNumber1 { get; set; }
        public decimal Amount { get; set; }
        public string IntegratorID { get; set; }
        public string TransactionID { get; set; }
        public string SerialNumber { get; set; }
        public string UserNameVended { get; set; }
        public string VTWEBUID { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public string CostOfUnits { get; set; }
        public string Units { get; set; }
        public string Tariff { get; set; }
        public int VoucherStatus { get; set; }
    }
}
